### ISSUE TITLE
1.20.1 Version?

### ISSUE THREAD

**Issue by Leniko141** [MokonaNico/IsometricCameraMod#6]
Hi i really love the mod, i always wanted something like that but is it possible to update the mod for other Minecraft versions? i honestly dont want to play without it anymore

**Comment by MokonaNico** [comment]
Thank you for your feedback! I'm glad you like the mod. Just wanted to let you know that I've added a release with the mod update for Minecraft version 1.20.1. 

I've quickly tested the update, and it seems to work seamlessly with Minecraft version 1.20.1. However, if you encounter any issues, please don't hesitate to open a new issue

**Comment by Leniko141** [comment]
wow thank you so much ^^ I wasn't even sure if I would get an answer
